version: '3.4'

services:
  bayraktar-gamebot:
    image: ${DOCKER_REGISTRY-}bayraktargamebot
    build:
      context: .
      dockerfile: BayraktarGameBot/Dockerfile
    container_name: bayraktar-gamebot-container
    env_file:
      - .env
    network_mode: host

